output "cluster_endpoint" {
  value       = module.eks.cluster_endpoint
  description = "Endpoint for EKS used by kubectl"
}

output "cluster_security_group_id" {
  value       = module.eks.cluster_security_group_id
  description = "Security group IDs used for cluster control plane"
}

output "kubectl_config" {
  value       = module.eks.kubeconfig
  description = "kubectl config which will be generated by the module"
}

output "config_map_aws_auth" {
  value       = module.eks.config_map_aws_auth
  description = "A kubernetes config to authenticate to EKS cluster"
}

output "region" {
  value       = var.region
  description = "AWS region"
}

output "cluster_name" {
  value       = local.cluster_name
  description = "K8 Cluster Name"
}
